### ISSUE TITLE
Compilation broken on Ubuntu 24.04

### ISSUE THREAD

**Issue by chrismile** [wildmeshing/fTetWild#79]
Hi,

When compiling fTetWild on Ubuntu 24.04, I receive the following errors:

```
[  0%] Building CXX object 3rdparty/fmt/CMakeFiles/fmt.dir/src/format.cc.o
[  0%] Building CXX object tbb/CMakeFiles/tbb_static.dir/src/old/concurrent_queue_v2.cpp.o
[  0%] Building CXX object tbb/CMakeFiles/tbb_static.dir/src/old/concurrent_vector_v2.cpp.o
In file included from /home/runner/work/DiffTetVR/DiffTetVR/third_party/fTetWild-src/3rdparty/tbb/src/old/concurrent_vector_v2.cpp:20:
/home/runner/work/DiffTetVR/DiffTetVR/third_party/fTetWild-src/3rdparty/tbb/include/tbb/task.h:274:20: error: declaration of ‘tbb::task& tbb::internal::task_prefix::task()’ changes meaning of ‘task’ [-Wchanges-meaning]
  274 |         tbb::task& task() {return *reinterpret_cast<tbb::task*>(this+1);}
      |                    ^~~~
/home/runner/work/DiffTetVR/DiffTetVR/third_party/fTetWild-src/3rdparty/tbb/include/tbb/task.h:233:9: note: used here to mean ‘class tbb::task’
  233 |         task* next_offloaded;
      |         ^~~~
/home/runner/work/DiffTetVR/DiffTetVR/third_party/fTetWild-src/3rdparty/tbb/include/tbb/task.h:29:7: note: declared here
   29 | class task;
      |       ^~~~
cc1plus: note: unrecognized command-line option ‘-Wno-keyword-macro’ may have been intended to silence earlier diagnostics
make[2]: *** [tbb/CMakeFiles/tbb_static.dir/build.make:93: tbb/CMakeFiles/tbb_static.dir/src/old/concurrent_vector_v2.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:1553: tbb/CMakeFiles/tbb_static.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

The same build process works on Ubuntu 22.04. Unfortunately, it seems like https://github.com/wjakob/tbb hasn't been updated in the last three years and might have incompatibilities with recent versions of GCC.

**Comment by chrismile** [comment]
Seems like the problem is that `-Wchanges-meaning` was introduced in GCC 13, and the TBB build treats warnings as errors.
I have fixed this issue in a fork at https://github.com/chrismile/fTetWild, where an updated version of TBB is used. I will leave this issue open until it is fixed in the upstream repo.
